spring.application.name=Seguridad
server.port=8083

# Datasource (variables de entorno)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

# Jackson
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# JWT
security.jwt.issuer=proyectodistri
security.jwt.secret=cambia-esto-por-un-secret-muy-largo-y-aleatorio
security.jwt.expiration-minutes=60
security.jwt.refresh-expiration-days=7  

DB_URL=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require&preferQueryMode=simple
DB_USER=postgres.encnohugezurvwmhzqnm
DB_PASS=Nicolas10#



