spring.application.name=proyecto-venta

# ---- Puerto del servicio ----
server.port=8081

# ---- Datasource: usar endpoint POOLED/transaction (puerto 6543) ----
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require&preferQueryMode=simple
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# ---- Hikari: pool chico para no reventar el límite del servidor ----
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=venta-pool

# ---- JPA/Hibernate ----
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ---- Liquibase desactivado en este microservicio ----
spring.liquibase.enabled=false
# (opcional) Si lo desactivás, podés comentar el changelog:
# spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# ---- Eureka ----
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ---- Logging ----
logging.level.root=INFO
logging.level.com.distri.proyectoVenta=INFO
logging.level.com.distri.proyectoVenta.apis.controller=INFO
logging.level.com.distri.proyectoVenta.apis.service=DEBUG
logging.level.com.distri.proyectoVenta.apis.repository=DEBUG
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO
logging.file.name=logs/app.log
spring.output.ansi.enabled=ALWAYS

# ---- JWT (mejor pasar por variables de entorno y NO commitear) ----
security.jwt.issuer=proyectodistri
security.jwt.secret=cambia-esto-por-un-secret-muy-largo-y-aleatorio
security.jwt.expiration-minutes=60
security.jwt.refresh-expiration-days=7  

# <<< NO USES COMILLAS >>>
DB_URL=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require&preferQueryMode=simple
DB_USER=postgres.encnohugezurvwmhzqnm
DB_PASS=Nicolas10#

# --- Redis como backend de caché ---
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASS:}
spring.data.redis.database=${REDIS_DB:0}


spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=${CACHE_PREFIX:venta:}


cache.ttl.categorias=60
cache.ttl.clientes=15
cache.ttl.compras=5
cache.ttl.productos=10
cache.ttl.proveedores=30

# Nivel de log para monitorear la actividad del caché
logging.level.com.distri.cache=DEBUG
