spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml


server.port: 8082
logging.level.root=INFO
logging.level.com.distri.proyectodistri=INFO
logging.level.com.distri.proyectodistri.apis.controller=INFO
logging.level.com.distri.proyectodistri.apis.service=DEBUG
logging.level.com.distri.proyectodistri.apis.repository=DEBUG
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


logging.file.name=logs/app.log

spring.output.ansi.enabled=ALWAYS

# ---- JWT (mejor pasar por variables de entorno y NO commitear) ----
security.jwt.issuer=proyectodistri
security.jwt.secret=cambia-esto-por-un-secret-muy-largo-y-aleatorio
security.jwt.expiration-minutes=60
security.jwt.refresh-expiration-days=7  

DB_URL=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require&preferQueryMode=simple
DB_USER=postgres.encnohugezurvwmhzqnm
DB_PASS=Nicolas10#

# --- Redis como backend de caché ---
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASS:}
spring.data.redis.database=${REDIS_DB:0}


spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=${CACHE_PREFIX:venta:}


cache.ttl.categorias=60
cache.ttl.clientes=15
cache.ttl.compras=5
cache.ttl.productos=10
cache.ttl.proveedores=30

# Nivel de log para monitorear la actividad del caché
logging.level.com.distri.cache=DEBUG
